import os
os.environ["SDL_VIDEODRIVER"] = "dummy"
os.environ["SDL_AUDIODRIVER"] = "dummy"

import sys
import glob
import pickle
import imageio
import numpy as np
import neat
import pygame
import json
import random
import simulation 

# --- CONFIGURATION ---
DAILY_GENERATIONS = 20  
VIDEO_OUTPUT_DIR = "training_clips"
FPS = 30 
MAX_FRAMES_PRO = 1800      # 60s for the daily best
MAX_FRAMES_TRAINING = 450  # 15s for progress clips

if not os.path.exists(VIDEO_OUTPUT_DIR): os.makedirs(VIDEO_OUTPUT_DIR)

# Try to load theme (if generated by simulation.py logic)
try:
    with open("theme.json", "r") as f: THEME = json.load(f)
except:
    THEME = {"map_seed": 42}

def create_config_file():
    # --- HYBRID CONFIG: YOUR STABLE SETTINGS + REQUIRED FIXES ---
    config_content = """
[NEAT]
fitness_criterion     = max
fitness_threshold     = 100000
pop_size              = 40
reset_on_extinction   = False
no_fitness_termination = False

[DefaultGenome]
activation_default      = tanh
activation_mutate_rate  = 0.0
activation_options      = tanh
aggregation_default     = sum
aggregation_mutate_rate = 0.0
aggregation_options     = sum

# --- YOUR STABLE MUTATION RATES ---
bias_init_mean          = 0.0
bias_init_stdev         = 1.0
bias_max_value          = 30.0
bias_min_value          = -30.0
bias_mutate_power       = 0.5
bias_replace_rate       = 0.1
bias_mutate_rate        = 0.2
bias_init_type          = gaussian

response_init_mean      = 1.0
response_init_stdev     = 0.0
response_max_value      = 30.0
response_min_value      = -30.0
response_mutate_power   = 0.0
response_replace_rate   = 0.0
response_mutate_rate    = 0.0
response_init_type      = gaussian

weight_init_mean        = 0.0
weight_init_stdev       = 1.0
weight_max_value        = 30
weight_min_value        = -30
weight_mutate_power     = 0.5
weight_replace_rate     = 0.1
weight_mutate_rate      = 0.3
weight_init_type        = gaussian

conn_add_prob           = 0.3
conn_delete_prob        = 0.3
enabled_default         = True
enabled_mutate_rate     = 0.01
feed_forward            = True
initial_connection      = full

enabled_rate_to_true_add = 0.0
enabled_rate_to_false_add = 0.0

# --- UPGRADED AI STRUCTURE ---
num_hidden              = 0
num_inputs              = 8  
# Inputs: 5 Radars + Angle + Dist + SPEED (New)
num_outputs             = 2

node_add_prob           = 0.1
node_delete_prob        = 0.1

# --- STRICT MODE FIXES (PREVENTS CRASHES) ---
compatibility_disjoint_coefficient = 1.0
compatibility_weight_coefficient   = 0.5
single_structural_mutation         = False
structural_mutation_surer          = default

[DefaultSpeciesSet]
compatibility_threshold = 3.0

[DefaultStagnation]
species_fitness_func = max
max_stagnation       = 20
species_elitism      = 2

[DefaultReproduction]
elitism            = 2
survival_threshold = 0.2
min_species_size   = 2
    """
    with open("config.txt", "w") as f:
        f.write(config_content)

def run_dummy_generation():
    """Runs a 'dumb' generation 0 just for the intro clip."""
    checkpoints = glob.glob("neat-checkpoint-*")
    if len(checkpoints) > 0: return

    print("\n--- 🤡 Running Dummy Gen 0 (Fresh Start) ---")
    pygame.init()
    screen = pygame.display.set_mode((simulation.WIDTH, simulation.HEIGHT))

    # Updated Map Generator Unpacking (Now includes skid_map)
    map_gen = simulation.TrackGenerator(seed=THEME["map_seed"])
    start_pos, phys_map, vis_map, skid_map, checkpoints, start_angle = map_gen.generate_track()
    
    camera = simulation.Camera(simulation.WORLD_SIZE, simulation.WORLD_SIZE)
    cars = [simulation.Car(start_pos, start_angle) for _ in range(40)]

    video_path = os.path.join(VIDEO_OUTPUT_DIR, "gen_00000.mp4")
    writer = imageio.get_writer(video_path, fps=FPS)

    running = True
    frame_count = 0
    
    while running and len(cars) > 0:
        frame_count += 1
        if frame_count > 300: break 
        for event in pygame.event.get():
            if event.type == pygame.QUIT: sys.exit()
            
        alive_cars = [c for c in cars if c.alive]
        if not alive_cars: break
        
        leader = max(alive_cars, key=lambda c: c.distance_traveled)
        camera.update(leader)
        for c in cars: c.is_leader = (c == leader)
        
        for car in cars:
            if not car.alive: continue
            if random.random() < 0.1: car.steering = random.choice([-1, 0, 1])
            car.input_gas()
            # UPDATED: Pass both maps to update
            car.update(phys_map, skid_map)
            
        # Draw: BG -> Track -> Skids -> Cars
        sub_rect = camera.camera
        screen.fill(simulation.COL_BG)
        try:
            screen.blit(vis_map, (0,0), area=sub_rect)
            screen.blit(skid_map, (0,0), area=sub_rect)
        except: pass
        
        for car in cars: car.draw(screen, camera)
        
        # Overlay
        font = pygame.font.SysFont("consolas", 40, bold=True)
        screen.blit(font.render("GEN 0 (NOOB)", True, simulation.COL_WALL), (20, 20))
        
        pygame.display.flip()
        try:
            pixels = pygame.surfarray.array3d(screen)
            pixels = np.transpose(pixels, (1, 0, 2))
            writer.append_data(pixels)
        except: pass
        
    writer.close()
    print("✅ Gen 0 Saved.")

# Global state
START_GEN = 0
FINAL_GEN = 0
GENERATION = 0

def run_simulation(genomes, config):
    global GENERATION
    GENERATION += 1 
    print(f"\n--- 🏁 Gen {GENERATION} ---")

    nets = []
    cars = []
    ge = []

    pygame.init()
    screen = pygame.display.set_mode((simulation.WIDTH, simulation.HEIGHT))

    # Updated Map Unpacking
    map_gen = simulation.TrackGenerator(seed=THEME["map_seed"])
    start_pos, phys_map, vis_map, skid_map, checkpoints, start_angle = map_gen.generate_track()
    
    camera = simulation.Camera(simulation.WORLD_SIZE, simulation.WORLD_SIZE)

    for _, g in genomes:
        net = neat.nn.FeedForwardNetwork.create(g, config)
        nets.append(net)
        cars.append(simulation.Car(start_pos, start_angle)) 
        g.fitness = 0
        ge.append(g)

    writer = None
    
    # Smart Recording Logic
    is_first_of_day = (GENERATION == START_GEN + 1)
    is_milestone = (GENERATION % 10 == 0)
    is_last_of_day = (GENERATION >= FINAL_GEN)
    should_record = is_first_of_day or is_milestone or is_last_of_day

    if should_record:
        filename = f"gen_{GENERATION:05d}.mp4"
        video_path = os.path.join(VIDEO_OUTPUT_DIR, filename)
        print(f"🎥 Recording Gen {GENERATION}...")
        writer = imageio.get_writer(video_path, fps=FPS)

    running = True
    frame_count = 0
    
    # Pre-check radars
    for car in cars: car.check_radar(phys_map)
    
    current_max_frames = MAX_FRAMES_PRO if is_last_of_day else MAX_FRAMES_TRAINING

    while running and len(cars) > 0:
        frame_count += 1
        if frame_count > current_max_frames: break

        for event in pygame.event.get():
            if event.type == pygame.QUIT: sys.exit()

        # Find leader
        leader = max(cars, key=lambda c: c.gates_passed * 1000 + c.distance_traveled)
        camera.update(leader)
        for c in cars: c.is_leader = (c == leader)

        for i, car in enumerate(cars):
            if not car.alive: continue

            # --- 8 INPUTS FOR AI ---
            # 1. Radar (5)
            if len(car.radars) < 5: radar_inputs = [0] * 5
            else: radar_inputs = [d[1] / simulation.SENSOR_LENGTH for d in car.radars]
            
            # 2. Telemetry (3: Angle, Dist, Speed)
            telemetry = car.get_data(checkpoints)
            
            # Combine
            final_inputs = radar_inputs + telemetry

            # Activate
            output = nets[i].activate(final_inputs)
            if output[0] > 0.5: car.input_steer(right=True)
            elif output[0] < -0.5: car.input_steer(left=True)

            car.input_gas()
            
            # UPDATED: Physics Update (Pass both maps)
            car.update(phys_map, skid_map)
            car.check_radar(phys_map)

            # Fitness Rewards
            if car.check_gates(checkpoints):
                ge[i].fitness += 200

            # Reward speed/distance
            dist_score = 1.0 - telemetry[1] 
            ge[i].fitness += dist_score * 0.1
            ge[i].fitness += car.speed * 0.05 # Reward going fast

            # Punishments
            if not car.alive:
                 ge[i].fitness -= 50

            if not car.alive and car.frames_since_gate > 450:
                 ge[i].fitness -= 20

        # Remove dead cars
        for i in range(len(cars) - 1, -1, -1):
            if not cars[i].alive:
                cars.pop(i)
                nets.pop(i)
                ge.pop(i)

        # Draw Frame
        if should_record or frame_count % 10 == 0:
            sub_rect = camera.camera
            screen.fill(simulation.COL_BG)
            try:
                screen.blit(vis_map, (0,0), area=sub_rect)
                screen.blit(skid_map, (0,0), area=sub_rect)
            except: pass
            
            for car in cars: car.draw(screen, camera)

            # HUD
            font = pygame.font.SysFont("consolas", 40, bold=True)
            seconds = int(frame_count / FPS)
            screen.blit(font.render(f"{seconds}s", True, (255, 255, 255)), (20, 60))
            screen.blit(font.render(f"GEN {GENERATION}", True, simulation.COL_WALL), (20, 20))
            pygame.display.flip()

            if writer:
                try:
                    pixels = pygame.surfarray.array3d(screen)
                    pixels = np.transpose(pixels, (1, 0, 2))
                    writer.append_data(pixels)
                except: pass

    if writer: writer.close()

def run_neat(config_path):
    global GENERATION, START_GEN, FINAL_GEN

    # Cleanup old clips
    for f in glob.glob(os.path.join(VIDEO_OUTPUT_DIR, "*.mp4")):
        try: os.remove(f)
        except: pass

    # Restore Checkpoint logic
    checkpoints = [f for f in os.listdir(".") if f.startswith("neat-checkpoint-")]

    if checkpoints:
        latest = sorted(checkpoints, key=lambda x: int(x.split('-')[2]))[-1]
        print(f"🧠 RESTORING SUPER-BRAIN FROM: {latest}")
        START_GEN = int(latest.split('-')[2])
        GENERATION = START_GEN
        p = neat.Checkpointer.restore_checkpoint(latest)
    else:
        print("👶 NO BRAIN FOUND. BIRTH OF A NEW SPECIES.")
        run_dummy_generation() # Runs Gen 0
        START_GEN = 0
        GENERATION = 0
        config = neat.config.Config(neat.DefaultGenome, neat.DefaultReproduction,
                                    neat.DefaultSpeciesSet, neat.DefaultStagnation,
                                    config_path)
        p = neat.Population(config)

    FINAL_GEN = START_GEN + DAILY_GENERATIONS
    print(f"🎯 MISSION: Evolve from Gen {START_GEN} -> Gen {FINAL_GEN}")

    p.add_reporter(neat.StdOutReporter(True))
    p.add_reporter(neat.Checkpointer(generation_interval=5, filename_prefix="neat-checkpoint-"))

    p.run(run_simulation, DAILY_GENERATIONS)

if __name__ == "__main__":
    create_config_file()
    local_dir = os.path.dirname(__file__)
    config_path = os.path.join(local_dir, "config.txt")
    run_neat(config_path)
